site_name: RED FLAGS Documentation
site_author: Zsolt Jurányi
site_description: "User, maintainer and developer documentation of the RED FLAGS tool"
site_favicon: favicon.ico
copyright: "<a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'><img alt='Creative Commons License' style='border-width:0;margin-bottom:5px' src='https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png' /></a> <br> This work is licensed under a <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a> <br> <b>Copyright &copy; 2016, PetaByte Research Ltd.</b>"
#theme: simplex
theme_dir: simplex-custom
markdown_extensions:
    - markdown_include.include       # pip install markdown-include
pages:
- Home:                              index.md
- For users:
  - Navigating on the site:          user/navigation.md
  - User accounts:                   user/accounts.md
  - Browsing notices:                user/notices.md
  - Browsing organizations:          user/organizations.md
  - List of indicators:              user/indicators.md
- For administrators:
  - System overview:                 maintainer/overview.md
  - About the database:              maintainer/database.md
  - Maintaining the engine:          maintainer/engine.md
  - Maintaining the webapp:          maintainer/webapp.md
  - Setting up the cron script:      maintainer/cron.md
- For developers:
  - Getting started:                 developer/first.md
  - Data model:
    - Data overview:                 developer/data/index.md
    - Data classes:                  developer/data/classes.md
    - Tables of the engine:          developer/data/engine-tables.md
    - Tables of the webapp:          developer/data/webapp-tables.md
  - Engine:
    - Understanding the engine:      developer/engine/index.md
    - Gears:
      - Downloader gears:            developer/engine/gears/downloaders.md
      - Parser gears:                developer/engine/gears/parsers.md
      - Filter gears:                developer/engine/gears/filters.md
      - Indicator gears:             developer/engine/gears/filters.md
      - Exporter gears:              developer/engine/gears/exporters.md
    - TED Interface:                 developer/engine/tedinterface.md
    - Template parser:               developer/engine/templateparser.md
  - Webapp:
    - Webapp basics:                 developer/webapp/basic.md
    - ControllerAdvice beans:        developer/webapp/controller-advices.md
    - Controllers:                   developer/webapp/controllers.md
    - Views:                         developer/webapp/views.md
    - Services:                      developer/webapp/services.md
    - How notice filters work:       developer/webapp/filters.md
  - Cookbook for extending:          developer/cookbook.md